name: downloader

on:
  issues:
    types: [opened]

jobs:
  get-file:
    if: startsWith(github.event.issue.title, 'DOWNLOAD:')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract URL
        id: extract_url
        run: |
          TITLE="${{ github.event.issue.title }}"
          URL=${TITLE#DOWNLOAD:}
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "filename=$(basename "$URL")" >> $GITHUB_OUTPUT

      - name: Download File
        run: |
          curl -L -H "User-Agent: Mozilla/5.0" -o "${{ steps.extract_url.outputs.filename }}" "${{ steps.extract_url.outputs.url }}"

      - name: Commit and Push to repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add "${{ steps.extract_url.outputs.filename }}"
          git commit -m "Add downloaded file: ${{ steps.extract_url.outputs.filename }}"
          git push
